import { Offer } from '../types/Offer';

export const offers: Offer[] = [
  // PARIS
  {
    id: '1',
    title: 'Beautiful apartment in the heart of Paris',
    type: 'Apartment',
    price: 150,
    city: 'Paris',
    isFavorite: false,
    isPremium: true,
    latitude: 48.8566,
    longitude: 2.3522,
    rating: 5,
    previewImage: 'img/apartment-01.jpg',
    images: ['img/apartment-01.jpg', 'img/apartment-02.jpg', 'img/room.jpg'],
    bedrooms: 2,
    maxAdults: 4,
    description: 'Cozy apartment near Eiffel Tower with amazing views.',
    inside: ['Wi-Fi', 'Washing machine', 'Kitchen', 'Air conditioning'],
    host: {
      name: 'Marie',
      avatar: 'img/avatar-angelina.jpg',
      isPro: true,
      description: 'Professional host with years of experience.',
    },
    reviews: [
      {
        id: 'r1',
        user: 'John',
        avatar: 'img/avatar-max.jpg',
        rating: 5,
        text: 'Amazing location and very clean!',
        date: 'December 2023',
      },
    ],
  },
  {
    id: '2',
    title: 'Studio near Louvre Museum',
    type: 'Studio',
    price: 120,
    city: 'Paris',
    isFavorite: false,
    isPremium: false,
    latitude: 48.8606,
    longitude: 2.3376,
    rating: 4,
    previewImage: 'img/studio-01.jpg',
    images: ['img/studio-01.jpg'],
    bedrooms: 1,
    maxAdults: 2,
    description: 'Small but comfortable studio.',
    inside: ['Wi-Fi', 'Kitchen'],
    host: {
      name: 'Pierre',
      avatar: 'img/avatar-angelina.jpg',
      isPro: false,
      description: 'Local resident.',
    },
    reviews: [],
  },
  {
    id: '3',
    title: 'Modern room in Marais district',
    type: 'Room',
    price: 80,
    city: 'Paris',
    isFavorite: true,
    isPremium: false,
    latitude: 48.8597,
    longitude: 2.3624,
    rating: 4,
    previewImage: 'img/room.jpg',
    images: ['img/room.jpg'],
    bedrooms: 1,
    maxAdults: 2,
    description: 'Charming room in historic district.',
    inside: ['Wi-Fi'],
    host: {
      name: 'Sophie',
      avatar: 'img/avatar-angelina.jpg',
      isPro: true,
      description: 'Friendly host.',
    },
    reviews: [],
  },

  // AMSTERDAM
  {
    id: '4',
    title: 'Nice, cozy, warm big bed apartment',
    type: 'Apartment',
    price: 180,
    city: 'Amsterdam',
    isFavorite: false,
    isPremium: true,
    latitude: 52.3809553943508,
    longitude: 4.939309666406198,
    rating: 5,
    previewImage: 'img/apartment-03.jpg',
    images: [
      'img/apartment-03.jpg',
      'img/apartment-02.jpg',
      'img/room.jpg',
      'img/apartment-01.jpg',
      'img/studio-01.jpg',
    ],
    bedrooms: 2,
    maxAdults: 4,
    description:
      'Premium apartment with all modern amenities and comfort. Large bed and spacious rooms.',
    inside: [
      'Wi-Fi',
      'Washing machine',
      'Towels',
      'Heating',
      'Coffee machine',
      'Kitchen',
      'Dishwasher',
      'Cable TV',
      'Fridge',
      'Air conditioning',
    ],
    host: {
      name: 'Isabella',
      avatar: 'img/avatar-angelina.jpg',
      isPro: true,
      description:
        'Luxury apartment host with attention to every detail. Your comfort is our priority.',
    },
    reviews: [
      {
        id: 'r5',
        user: 'Laura',
        avatar: 'img/avatar-max.jpg',
        rating: 5,
        text: 'Absolutely amazing! The apartment is beautiful and the host is very responsive.',
        date: 'December 2018',
      },
      {
        id: 'r6',
        user: 'James',
        avatar: 'img/avatar-angelina.jpg',
        rating: 5,
        text: 'Perfect luxury experience. Would recommend to everyone!',
        date: 'November 2018',
      },
    ],
  },
  {
    id: '5',
    title: 'Cozy room with canal view',
    type: 'Room',
    price: 95,
    city: 'Amsterdam',
    isFavorite: false,
    isPremium: false,
    latitude: 52.3676,
    longitude: 4.9041,
    rating: 4,
    previewImage: 'img/room.jpg',
    images: ['img/room.jpg'],
    bedrooms: 1,
    maxAdults: 2,
    description: 'Beautiful room overlooking Amsterdam canals.',
    inside: ['Wi-Fi', 'Heating'],
    host: {
      name: 'Jan',
      avatar: 'img/avatar-max.jpg',
      isPro: true,
      description: 'Experienced host.',
    },
    reviews: [],
  },
  {
    id: '6',
    title: 'Spacious apartment near Central Station',
    type: 'Apartment',
    price: 200,
    city: 'Amsterdam',
    isFavorite: false,
    isPremium: true,
    latitude: 52.3792,
    longitude: 4.8956,
    rating: 5,
    previewImage: 'img/apartment-02.jpg',
    images: ['img/apartment-02.jpg'],
    bedrooms: 3,
    maxAdults: 6,
    description: 'Spacious and modern apartment in prime location.',
    inside: ['Wi-Fi', 'Washing machine', 'Kitchen', 'Dishwasher'],
    host: {
      name: 'Anna',
      avatar: 'img/avatar-angelina.jpg',
      isPro: true,
      description: 'Professional management.',
    },
    reviews: [],
  },

  // COLOGNE
  {
    id: '7',
    title: 'Historic apartment near Cathedral',
    type: 'Apartment',
    price: 140,
    city: 'Cologne',
    isFavorite: false,
    isPremium: true,
    latitude: 50.9406,
    longitude: 6.9585,
    rating: 5,
    previewImage: 'img/apartment-01.jpg',
    images: ['img/apartment-01.jpg'],
    bedrooms: 2,
    maxAdults: 4,
    description: 'Beautiful apartment in historic city center.',
    inside: ['Wi-Fi', 'Kitchen', 'Heating'],
    host: {
      name: 'Klaus',
      avatar: 'img/avatar-max.jpg',
      isPro: true,
      description: 'Local expert.',
    },
    reviews: [],
  },
  {
    id: '8',
    title: 'Modern studio with river view',
    type: 'Studio',
    price: 110,
    city: 'Cologne',
    isFavorite: false,
    isPremium: false,
    latitude: 50.9548,
    longitude: 6.9604,
    rating: 4,
    previewImage: 'img/studio-01.jpg',
    images: ['img/studio-01.jpg'],
    bedrooms: 1,
    maxAdults: 2,
    description: 'Small modern studio with nice view.',
    inside: ['Wi-Fi'],
    host: {
      name: 'Heidi',
      avatar: 'img/avatar-angelina.jpg',
      isPro: false,
      description: 'Friendly host.',
    },
    reviews: [],
  },

  // BRUSSELS
  {
    id: '9',
    title: 'Elegant apartment in the center',
    type: 'Apartment',
    price: 160,
    city: 'Brussels',
    isFavorite: false,
    isPremium: true,
    latitude: 50.8503,
    longitude: 4.3517,
    rating: 5,
    previewImage: 'img/apartment-03.jpg',
    images: ['img/apartment-03.jpg'],
    bedrooms: 2,
    maxAdults: 4,
    description: 'Elegant apartment near Grand Place.',
    inside: ['Wi-Fi', 'Washing machine', 'Kitchen'],
    host: {
      name: 'Luc',
      avatar: 'img/avatar-max.jpg',
      isPro: true,
      description: 'Professional host.',
    },
    reviews: [],
  },
  {
    id: '10',
    title: 'Budget room near train station',
    type: 'Room',
    price: 70,
    city: 'Brussels',
    isFavorite: false,
    isPremium: false,
    latitude: 50.8363,
    longitude: 4.3613,
    rating: 3,
    previewImage: 'img/room.jpg',
    images: ['img/room.jpg'],
    bedrooms: 1,
    maxAdults: 1,
    description: 'Budget option near station.',
    inside: ['Wi-Fi'],
    host: {
      name: 'Francine',
      avatar: 'img/avatar-angelina.jpg',
      isPro: false,
      description: 'Local resident.',
    },
    reviews: [],
  },

  // HAMBURG
  {
    id: '11',
    title: 'Modern apartment near port',
    type: 'Apartment',
    price: 170,
    city: 'Hamburg',
    isFavorite: false,
    isPremium: true,
    latitude: 53.5511,
    longitude: 9.4979,
    rating: 5,
    previewImage: 'img/apartment-02.jpg',
    images: ['img/apartment-02.jpg'],
    bedrooms: 2,
    maxAdults: 4,
    description: 'Modern apartment with port views.',
    inside: ['Wi-Fi', 'Washing machine', 'Kitchen', 'Air conditioning'],
    host: {
      name: 'Helmut',
      avatar: 'img/avatar-max.jpg',
      isPro: true,
      description: 'Experienced host.',
    },
    reviews: [],
  },
  {
    id: '12',
    title: 'Cozy room in Altstadt',
    type: 'Room',
    price: 85,
    city: 'Hamburg',
    isFavorite: false,
    isPremium: false,
    latitude: 53.5401,
    longitude: 9.9845,
    rating: 4,
    previewImage: 'img/room.jpg',
    images: ['img/room.jpg'],
    bedrooms: 1,
    maxAdults: 2,
    description: 'Charming room in historic district.',
    inside: ['Wi-Fi', 'Heating'],
    host: {
      name: 'Greta',
      avatar: 'img/avatar-angelina.jpg',
      isPro: false,
      description: 'Friendly local host.',
    },
    reviews: [],
  },

  // DUSSELDORF
  {
    id: '13',
    title: 'Luxury penthouse apartment',
    type: 'Apartment',
    price: 250,
    city: 'Dusseldorf',
    isFavorite: false,
    isPremium: true,
    latitude: 51.2277,
    longitude: 6.7735,
    rating: 5,
    previewImage: 'img/apartment-03.jpg',
    images: ['img/apartment-03.jpg'],
    bedrooms: 3,
    maxAdults: 6,
    description: 'Luxury penthouse with panoramic views.',
    inside: [
      'Wi-Fi',
      'Washing machine',
      'Kitchen',
      'Air conditioning',
      'Dishwasher',
    ],
    host: {
      name: 'Wolfgang',
      avatar: 'img/avatar-max.jpg',
      isPro: true,
      description: 'Premium host.',
    },
    reviews: [],
  },
  {
    id: '14',
    title: 'Standard studio apartment',
    type: 'Studio',
    price: 125,
    city: 'Dusseldorf',
    isFavorite: false,
    isPremium: false,
    latitude: 51.2358,
    longitude: 6.802,
    rating: 4,
    previewImage: 'img/studio-01.jpg',
    images: ['img/studio-01.jpg'],
    bedrooms: 1,
    maxAdults: 2,
    description: 'Standard modern studio.',
    inside: ['Wi-Fi', 'Kitchen'],
    host: {
      name: 'Sabine',
      avatar: 'img/avatar-angelina.jpg',
      isPro: false,
      description: 'Helpful host.',
    },
    reviews: [],
  },
];
