import { Offer } from '../types/Offer';

export const offers: Offer[] = [
  {
    id: '1',
    title: 'Beautiful & luxurious studio at great location',
    type: 'Apartment',
    price: 120,
    city: 'Amsterdam',
    isFavorite: false,
    isPremium: true,
    rating: 4.8,
    previewImage: 'img/apartment-01.jpg',
    images: [
      'img/apartment-01.jpg',
      'img/room.jpg',
      'img/apartment-02.jpg',
      'img/apartment-03.jpg',
      'img/studio-01.jpg',
    ],
    bedrooms: 3,
    maxAdults: 4,
    description:
      'A quiet cozy and picturesque apartment that hides behind a river by the unique lightness of Amsterdam. The building is green and from 18th century.',
    inside: [
      'Wi-Fi',
      'Washing machine',
      'Towels',
      'Heating',
      'Coffee machine',
      'Baby seat',
      'Kitchen',
      'Dishwasher',
      'Cable TV',
      'Fridge',
    ],
    host: {
      name: 'Angelina',
      avatar: 'img/avatar-angelina.jpg',
      isPro: true,
      description:
        'A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century. An independent House, strategically located between Rembrandt Square and National Opera, but where the bustle of the city comes to rest in this alley flowery and colorful.',
    },
    reviews: [
      {
        id: 'r1',
        user: 'Max',
        avatar: 'img/avatar-max.jpg',
        rating: 4,
        text: 'A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.',
        date: 'April 2019',
      },
    ],
  },
  {
    id: '2',
    title: 'Wood and stone place',
    type: 'Room',
    price: 80,
    city: 'Amsterdam',
    isFavorite: true,
    isPremium: false,
    rating: 4,
    previewImage: 'img/room.jpg',
    images: ['img/room.jpg', 'img/apartment-01.jpg', 'img/apartment-02.jpg'],
    bedrooms: 1,
    maxAdults: 2,
    description:
      'Cozy room with wooden interior and stone accents. Perfect for a peaceful stay.',
    inside: ['Wi-Fi', 'Heating', 'Kitchen'],
    host: {
      name: 'John',
      avatar: 'img/avatar-angelina.jpg',
      isPro: false,
      description:
        'Friendly local host who loves helping guests discover Amsterdam.',
    },
    reviews: [
      {
        id: 'r2',
        user: 'Emma',
        avatar: 'img/avatar-max.jpg',
        rating: 4,
        text: 'Great location and very comfortable space.',
        date: 'March 2019',
      },
      {
        id: 'r3',
        user: 'Michael',
        avatar: 'img/avatar-angelina.jpg',
        rating: 5,
        text: 'Excellent host and beautiful room. Will definitely come back!',
        date: 'February 2019',
      },
    ],
  },
  {
    id: '3',
    title: 'Canal View Prinsengracht',
    type: 'Apartment',
    price: 132,
    city: 'Amsterdam',
    isFavorite: false,
    isPremium: false,
    rating: 4.5,
    previewImage: 'img/apartment-02.jpg',
    images: [
      'img/apartment-02.jpg',
      'img/apartment-01.jpg',
      'img/room.jpg',
      'img/apartment-03.jpg',
    ],
    bedrooms: 2,
    maxAdults: 3,
    description:
      'Stunning canal-facing apartment with traditional Amsterdam architecture.',
    inside: [
      'Wi-Fi',
      'Washing machine',
      'Towels',
      'Heating',
      'Kitchen',
      'Dishwasher',
    ],
    host: {
      name: 'Sophie',
      avatar: 'img/avatar-max.jpg',
      isPro: true,
      description:
        'Professional host with years of experience in hospitality. We ensure every guest has a memorable stay.',
    },
    reviews: [
      {
        id: 'r4',
        user: 'David',
        avatar: 'img/avatar-angelina.jpg',
        rating: 4,
        text: 'Perfect location with beautiful views of the canal.',
        date: 'January 2019',
      },
    ],
  },
  {
    id: '4',
    title: 'Nice, cozy, warm big bed apartment',
    type: 'Apartment',
    price: 180,
    city: 'Amsterdam',
    isFavorite: false,
    isPremium: true,
    rating: 5,
    previewImage: 'img/apartment-03.jpg',
    images: [
      'img/apartment-03.jpg',
      'img/apartment-02.jpg',
      'img/room.jpg',
      'img/apartment-01.jpg',
      'img/studio-01.jpg',
    ],
    bedrooms: 2,
    maxAdults: 4,
    description:
      'Premium apartment with all modern amenities and comfort. Large bed and spacious rooms.',
    inside: [
      'Wi-Fi',
      'Washing machine',
      'Towels',
      'Heating',
      'Coffee machine',
      'Kitchen',
      'Dishwasher',
      'Cable TV',
      'Fridge',
      'Air conditioning',
    ],
    host: {
      name: 'Isabella',
      avatar: 'img/avatar-angelina.jpg',
      isPro: true,
      description:
        'Luxury apartment host with attention to every detail. Your comfort is our priority.',
    },
    reviews: [
      {
        id: 'r5',
        user: 'Laura',
        avatar: 'img/avatar-max.jpg',
        rating: 5,
        text: 'Absolutely amazing! The apartment is beautiful and the host is very responsive.',
        date: 'December 2018',
      },
      {
        id: 'r6',
        user: 'James',
        avatar: 'img/avatar-angelina.jpg',
        rating: 5,
        text: 'Perfect luxury experience. Would recommend to everyone!',
        date: 'November 2018',
      },
    ],
  },
  {
    id: '5',
    title: 'Studio near Central Station',
    type: 'Room',
    price: 75,
    city: 'Amsterdam',
    isFavorite: true,
    isPremium: false,
    rating: 3.9,
    previewImage: 'img/studio-01.jpg',
    images: ['img/studio-01.jpg', 'img/room.jpg', 'img/apartment-01.jpg'],
    bedrooms: 1,
    maxAdults: 2,
    description:
      'Budget-friendly studio in walking distance from Central Station.',
    inside: ['Wi-Fi', 'Heating', 'Kitchen', 'Washing machine'],
    host: {
      name: 'Peter',
      avatar: 'img/avatar-max.jpg',
      isPro: false,
      description:
        'Local Amsterdam resident, happy to share tips about the city.',
    },
    reviews: [
      {
        id: 'r7',
        user: 'Sarah',
        avatar: 'img/avatar-angelina.jpg',
        rating: 4,
        text: 'Great value for money. Location is excellent!',
        date: 'October 2018',
      },
    ],
  },
];
